version: '2'

services:
  rethinkdb:
    image: rethinkdb:2.3.6
    ports:
     - "28015"
    volumes:
     - /tmp/data:/data
    command: rethinkdb --bind all --data /data

  managemystuff:
    image: istherepie/managemystuff:v0.0.1
    depends_on:
      - rethinkdb
    ports:
     - "5000:5000"
